name: kube-lint
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create ../results directory for SARIF report files
        shell: bash
        run: mkdir -p ../results

      - name: Scan yamls
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: exemplo/k8s-yaml
          config: exemplo/.kube-linter-config.yaml
          format: sarif
          output-file: ../results/kube-linter.sarif
        continue-on-error: true

#      - name: Upload SARIF report files to GitHub
#        uses: github/codeql-action/upload-sarif@v1

      # Ensure the workflow eventually fails if files did not pass kube-linter checks.
      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-lint-scan.outcome }}" == "success" ]]
